-- NPC Kill Log - RuneScape: Dragonwilds
--
-- Counts every NPC you kill, per character, and shows the counts in a window:
--   Goblin Warrior: 55
--   Giant Rat: 94
--
-- How it works:
--   * Kills: the Blueprint event BP_DominionAICharacter_C:BP_OnDeath, which runs once for every
--     creature that dies (not on unload, not for the player). The hook can only be registered once
--     the Blueprint is loaded, so it is retried every few seconds until a world is up. A kill counts
--     when the local player's pawn is in the dead AI's damage list (its controller's
--     ThreatSystem.DamageInstigators), so kills made by other players in co-op are left out
--     (OnlyMyKills).
--     The first version used AiAttackTicketsManager:OnAiDeath(ai) with
--     AIAudioManagerComponent:HandleDeath(ai) as a backup; they are kept commented out below
--     in case this hook stops working. ProgressComponent:OnAIKilled looks like the obvious event
--     but is called straight from C++, so a Lua hook on it never runs (checked with a probe,
--     2026-09-28).
--   * Names: the killed character's AI data row name (AIDataTableRowHandle.RowName, read from the
--     character or its AI controller, whichever has it) and its class
--     name are looked up in the game's own AI name string tables (npc_names.lua, generated by
--     tools/gen_npc_names.py). names.txt can override any name.
--   * Saving: one plain text file per character next to the game's saves,
--     %LOCALAPPDATA%\RSDragonwilds\Saved\NpcKillLog-<name>-<id>.txt, one "Name: count" line per NPC.
--     It is rewritten a couple of seconds after each kill, so it is always readable by hand too.
--   * Window: the game's own framed panel (WBP_Panel) with a search box and a scrolling list.
--     Opened from an NPC KILL LOG entry added to the pause menu (Esc), or optionally a key
--     (OpenKey, off by default). The pause menu is resumed first, since the pause menu's
--     backdrop draws over any window added to the viewport while it is up.
--     Esc or its CLOSE button closes it.
--   * Kill message: after each kill a line of text shows for a few seconds, for example
--     "Your Goblin Warrior kill count is now: 5." (MessageSeconds). Bosses and other NPCs have
--     their own on/off switch (ShowBossKillMessages, ShowKillMessages), also flipped with the two
--     buttons in the window, which save to toggles.txt. A boss is anything the game gives a boss
--     health bar, anything built on the game's miniboss base classes, and anything with "Boss" in
--     its class name, plus ExtraBosses and minus NotBosses from config.txt.

local TAG = "[NpcKillLog] "
local function log(msg) print(TAG .. tostring(msg) .. "\n") end

local cfg = {
    ShowInPauseMenu = true,
    MenuLabel = "NPC KILL LOG",
    OpenKey = "",           -- empty = no key, the pause menu entry only
    SortBy = "count",       -- count or name
    FontSize = 18,
    PanelWidth = 560,
    PanelHeight = 640,
    CaptureMouse = true,
    ShowKillMessages = true,       -- messages for regular NPCs
    ShowBossKillMessages = true,   -- messages for bosses and minibosses
    ExtraBosses = "",              -- comma separated shown names that also count as bosses
    NotBosses = "",                -- comma separated shown names that never count as bosses
    MessageSeconds = 4,
    MessageFontSize = 22,
    LogKills = true,
    OnlyMyKills = true,            -- false = count every NPC death, whoever made the kill
}

-- ---------------------------------------------------------------------------
-- Config
-- ---------------------------------------------------------------------------

-- The mod folder is the parent of the Scripts folder this file runs from
local function modFolder()
    local info = debug.getinfo(1, "S")
    local path = (info and info.source or ""):gsub("\\", "/")
    if path:sub(1, 1) == "@" then path = path:sub(2) end
    return path:match("^(.*)/Scripts/[^/]*$")
end

local function trim(s)
    return (s:match("^%s*(.-)%s*$"))
end

-- Calls fn(key, value) for every "Key = value" line of a text file; anything after # is a comment
local function readKeyValueFile(path, fn)
    local f = io.open(path, "r")
    if not f then return false end
    for raw in f:lines() do
        local text = trim((raw:gsub("#.*$", "")))
        local eq = text:find("=", 1, true)
        if eq then fn(trim(text:sub(1, eq - 1)), trim(text:sub(eq + 1))) end
    end
    f:close()
    return true
end

local function loadConfig(folder)
    local found = readKeyValueFile(folder .. "/config.txt", function(key, value)
        local default = cfg[key]
        if default == nil then
            log("unknown config key ignored: " .. key)
        elseif type(default) == "number" then
            local n = tonumber(value)
            if n then cfg[key] = math.floor(n) else log("not a number for " .. key .. ": " .. value) end
        elseif type(default) == "boolean" then
            local lower = value:lower()
            cfg[key] = (lower == "true" or lower == "yes" or lower == "1")
        else
            cfg[key] = value
        end
    end)
    if not found then log("no config.txt found, using defaults") end
end

local MOD_FOLDER = modFolder() or "."
loadConfig(MOD_FOLDER)

-- The on/off buttons in the window. Their state is kept in toggles.txt, which wins over
-- config.txt, so clicking them never rewrites the hand-edited config.txt
local TOGGLES = {
    { key = "ShowBossKillMessages", label = "BOSS KILL MESSAGES" },
    { key = "ShowKillMessages", label = "NPC KILL MESSAGES" },
}
local TOGGLES_FILE = MOD_FOLDER .. "/toggles.txt"

readKeyValueFile(TOGGLES_FILE, function(key, value)
    for _, t in ipairs(TOGGLES) do
        if t.key == key then cfg[key] = (value:lower() == "true") end
    end
end)

local function saveToggles()
    local f = io.open(TOGGLES_FILE, "w")
    if not f then
        log("cannot write " .. TOGGLES_FILE)
        return
    end
    f:write("# Set by the buttons in the NPC Kill Log window; these win over config.txt.\n")
    f:write("# Delete this file to go back to the config.txt values.\n")
    for _, t in ipairs(TOGGLES) do f:write(t.key .. " = " .. tostring(cfg[t.key]) .. "\n") end
    f:close()
end
cfg.FontSize = math.max(8, math.min(48, cfg.FontSize))
cfg.MessageFontSize = math.max(8, math.min(48, cfg.MessageFontSize))
cfg.MessageSeconds = math.max(1, math.min(60, cfg.MessageSeconds))
cfg.PanelWidth = math.max(300, math.min(2000, cfg.PanelWidth))
cfg.PanelHeight = math.max(250, math.min(1400, cfg.PanelHeight))

-- ---------------------------------------------------------------------------
-- Small helpers
-- ---------------------------------------------------------------------------

local function isValid(obj)
    if obj == nil then return false end
    local ok, v = pcall(function() return obj:IsValid() end)
    return ok and v == true
end

-- FText, FString and FName values all have ToString in UE4SS
local function toText(v)
    if v == nil then return nil end
    if type(v) == "string" then return v end
    local ok, s = pcall(function() return v:ToString() end)
    if ok and type(s) == "string" then return s end
    return nil
end

local function formatCount(n)
    local s = tostring(math.floor(n))
    local out = s
    while true do
        local replaced, count = out:gsub("^(%d+)(%d%d%d)", "%1,%2")
        out = replaced
        if count == 0 then return out end
    end
end

-- "1,234 kills of 23 NPC types", with "kill" and "NPC type" when the count is 1
local function killSummary(total, types)
    return formatCount(total) .. (total == 1 and " kill" or " kills") .. " of "
        .. formatCount(types) .. (types == 1 and " NPC type" or " NPC types")
end

-- "GoblinRuntBoss(Thug)" -> "Goblin Runt Boss (Thug)", "Medium_Beast" -> "Medium Beast"
local function prettify(s)
    s = s:gsub("_", " ")
    s = s:gsub("(%l)(%u)", "%1 %2"):gsub("(%u)(%u%l)", "%1 %2")
    s = s:gsub("(%a)%(", "%1 ("):gsub("(%a)(%d)", "%1 %2")
    return trim((s:gsub("%s+", " ")))
end

-- ---------------------------------------------------------------------------
-- NPC names
-- ---------------------------------------------------------------------------

local okNames, STRING_TABLE = pcall(require, "npc_names")
if not okNames or type(STRING_TABLE) ~= "table" then
    log("npc_names.lua could not be loaded, names will come from class names: " .. tostring(STRING_TABLE))
    STRING_TABLE = {}
end

-- Lookups ignore case and anything that is not a letter or digit
local function lookupKey(s)
    return (s:lower():gsub("[^%w]", ""))
end

local displayByKey = {}
for key, value in pairs(STRING_TABLE) do displayByKey[lookupKey(key)] = value end

-- AI data row names that are spelled differently from their string table key
local ROW_ALIASES = {
    ["GoblinAxe"] = "GoblinWarrior",
    ["GoblinRanger"] = "GoblinArcher",
    ["GoblinBruiser"] = "GoblinShield",
    ["GoblinPoisonRanger"] = "PoisonRangerGoblin",
    ["GoblinRuntBoss(Thug)"] = "PoisonRuntBoss",
    ["WolfAlpha"] = "DireWolf",
    ["Falcon"] = "Gyrfalcon",
    ["GarouBirdDruid(Wildcaller)"] = "BirdKingDruid",
    ["GarouSpinningBerserker"] = "GarouSpinner",
    ["GarouRanger"] = "GarouHunter",
    ["GarouThaneMini-Boss"] = "GarouKing",
    ["WildJadeVine"] = "JadeVine",
    ["VaultOverlord"] = "ColossalVaultGuardianMelee",
    ["VaultArchon"] = "ColossalVaultGuardianRanged",
    ["VaultMeleeMiniboss"] = "VaultMinibossMelee",
    ["BlackKnight1H"] = "BlackKnight1HMelee",
    ["BlackKnight2H"] = "BlackKnight2HMelee",
    ["BlackKnightCrusader(Flaming2H)"] = "BlackKnightCrusader",
    ["BlackKnightGuardian(SwSh)"] = "BlackKnightMelee",
    ["BlackKnightRanged"] = "BlackKnightCrossbow",
    ["StormboundDemon"] = "StormpactDemon",
    ["ZamorakAcolyte"] = "ZamorakianAcolyte",
    ["DragonLesserGreen"] = "DragonGreen",
    ["DragonImaru"] = "Imaru",
    ["DRZogre"] = "Zogre",
    ["RotriddenCow"] = "CowWithered",
    ["RotriddenRat"] = "GiantRatWithered",
    ["RotswornMarauder"] = "SkeletonMelee2hWither",
    ["RotswornNecromancer"] = "SkeletonWitherMage",
    ["RotswornWarrior"] = "SkeletonMeleeWithered",
    ["ImaruLostSoul"] = "LostSoul",
    ["ImaruRotswornMarauder"] = "SkeletonMelee2hWither",
    ["ImaruRotswornNecromancer"] = "SkeletonWitherMage",
    ["ImaruRotswornWarrior"] = "SkeletonMeleeWithered",
    ["SkeletalArcher"] = "SkeletonRanged",
    ["SkeletalHoplite"] = "SkeletonShield",
    ["SkeletalMarauder"] = "SkeletonMelee2H",
    ["SkeletalNecromancer"] = "SkeletonMage",
    ["SkeletalNecromancerRazlem"] = "SkeletalNecromancer_Razlem",
    ["SkeletalWarrior"] = "SkeletonMelee",
    ["SkeletonPoisonArcher(Blightshot)"] = "RotswornBlightShot",
    ["ZombieCow"] = "CowZombie",
    ["ZombieRat"] = "GiantRatZombie",
    ["DragonLesserBlack"] = "BlackDragon",
    ["DragonLesserBlackElite"] = "BlackDragon",
    ["Fuzan"] = "DragonFuzan",
    ["KalphiteQueenFlyer"] = "KalphiteQueen",
    ["KalphiteQueenGrounded"] = "KalphiteQueen",
    ["KalphiteQueenGuardianHatchling"] = "KalphiteQueenGuardianMinion",
    ["KalphiteQueenSoldierHatchling"] = "KalphiteQueenSoldierMinion",
    ["KalphiteQueenWorkerHatchling"] = "KalphiteQueenWorkerMinion",
    ["KotHaarHurFuzanMinion"] = "FuzanMinion",
    ["KotHaarKetFuzanMinion"] = "FuzanMinion",
    ["KotHaarXilFuzanMinion"] = "FuzanMinion",
    ["TokXil"] = "Tok-Xil",
    ["ThaneBeast_MiniBoss"] = "GarouKing",   -- a class name; the Garou King has no row name to go by
}

-- names.txt: "RowOrClassName = Shown Name" lines that win over everything else
local overrides = {}
readKeyValueFile(MOD_FOLDER .. "/names.txt", function(key, value)
    if key ~= "" and value ~= "" then overrides[lookupKey(key)] = value end
end)

local function shownName(key)
    if not key or key == "" or key == "None" then return nil end
    local k = lookupKey(key)
    return overrides[k] or displayByKey[k]
end

-- 'BP_AI_GiantRat_SW_Character_C' -> 'GiantRat_SW', 'BP_AI_Kebbit_Character_02_C' -> 'Kebbit'
-- (a numbered copy of a creature's blueprint is still the same creature)
local function classStem(className)
    local stem = className:gsub("_C$", ""):gsub("^BP_AI_", ""):gsub("^BP_", "")
    stem = stem:gsub("_%d+$", "")
    stem = stem:gsub("_Character$", "")
    return stem
end

local nameByClass = {}      -- class name -> resolved name, so each class is only worked out once
local loggedClasses = {}

-- The AI data row handle may live on the character or on its AI controller (the game binary lists
-- it among controller-looking properties), so try both; the first kill logs which one answered
local rowSourceLogged = false

local function rowNameOf(ai)
    local sources = { { "character", ai } }
    local ctrl = nil
    pcall(function() ctrl = ai.Controller end)
    if not isValid(ctrl) then pcall(function() ctrl = ai:GetController() end) end
    if isValid(ctrl) then sources[#sources + 1] = { "controller", ctrl } end
    for _, src in ipairs(sources) do
        local okR, rowName = pcall(function() return src[2].AIDataTableRowHandle.RowName:ToString() end)
        if okR and type(rowName) == "string" and rowName ~= "" and rowName ~= "None" then
            if not rowSourceLogged then
                rowSourceLogged = true
                log("AI data row names come from the " .. src[1])
            end
            return rowName
        end
    end
    if not rowSourceLogged then
        rowSourceLogged = true
        log("no AI data row name on the character or its controller (controller "
            .. (isValid(ctrl) and "found" or "not found") .. "); names come from class names")
    end
    return nil
end

local function resolveName(ai)
    local okC, className = pcall(function() return ai:GetClass():GetFName():ToString() end)
    className = okC and className or "Unknown"
    local rowName = rowNameOf(ai)

    local cacheKey = className .. "|" .. tostring(rowName)
    local cached = nameByClass[cacheKey]
    if cached then return cached end

    local stem = classStem(className)
    local name, how = nil, nil
    -- 1. an override or string table entry for the row name (or its known alias)
    if rowName then
        name = overrides[lookupKey(rowName)] or shownName(ROW_ALIASES[rowName] or rowName)
        how = name and "row " .. rowName
    end
    -- 2. the class name (or its known alias), whole ("HellHound_Minion_Fido") then without its last
    --    part, then its last part
    if not name then
        local tries = { ROW_ALIASES[stem] or stem, (stem:gsub("_[^_]*$", "")), stem:match("_([^_]+)$") }
        for _, t in ipairs(tries) do
            name = t and shownName(t)
            if name then how = "class " .. className; break end
        end
    end
    -- 3. a tidied up version of the row or class name
    if not name then
        name = prettify(rowName or stem)
        how = "fallback from " .. (rowName and ("row " .. rowName) or ("class " .. className))
    end

    nameByClass[cacheKey] = name
    if not loggedClasses[cacheKey] then
        loggedClasses[cacheKey] = true
        log("new NPC type: " .. className .. " (row " .. tostring(rowName) .. ") -> " .. name .. " [" .. how .. "]")
    end
    return name
end

-- ---------------------------------------------------------------------------
-- Character and save file
-- ---------------------------------------------------------------------------

local state = {
    key = nil,          -- save file key for the current character
    file = nil,
    kills = {},         -- shown name -> count
    savePending = false,
    pc = nil,
}

local function localController()
    if isValid(state.pc) then return state.pc end
    local ok, all = pcall(FindAllOf, "PlayerController")
    if not ok or not all then return nil end
    for _, pc in ipairs(all) do
        local okL, isLocal = pcall(function() return pc:IsLocalController() end)
        if isValid(pc) and okL and isLocal then
            state.pc = pc
            return pc
        end
    end
    return nil
end

local function savedFolder()
    local base = os.getenv("LOCALAPPDATA")
    if base and base ~= "" then return base .. "\\RSDragonwilds\\Saved" end
    return nil
end

-- The game's own character save holds a unique id, so a new character that reuses a deleted
-- character's name does not inherit its counts
local function characterGuid(folder, name)
    local f = io.open(folder .. "\\SaveCharacters\\" .. name .. ".json", "r")
    if not f then return nil end
    local text = f:read("*a")
    f:close()
    return text and text:match('"char_guid"%s*:%s*"(%x+)"')
end

local function loadCounts(path)
    local counts = {}
    local f = io.open(path, "r")
    if not f then
        f = io.open(path .. ".tmp", "r")   -- a save that was interrupted between write and rename
        if not f then return counts end
    end
    for line in f:lines() do
        if line:sub(1, 1) ~= "#" then
            local name, n = line:match("^(.-):%s*(%d+)%s*$")
            if name and name ~= "" then counts[name] = (counts[name] or 0) + tonumber(n) end
        end
    end
    f:close()
    return counts
end

-- filter is already a lookupKey (lower case, letters and digits only), so "giant rat",
-- "Giant-Rat" and "giantrat" all find Giant Rat even if a space or dash does not reach the box
local function sortedEntries(filter)
    local list = {}
    for name, n in pairs(state.kills) do
        if not filter or lookupKey(name):find(filter, 1, true) then
            list[#list + 1] = { name = name, count = n }
        end
    end
    if cfg.SortBy == "name" then
        table.sort(list, function(a, b) return a.name:lower() < b.name:lower() end)
    else
        table.sort(list, function(a, b)
            if a.count ~= b.count then return a.count > b.count end
            return a.name:lower() < b.name:lower()
        end)
    end
    return list
end

local function saveNow()
    state.savePending = false
    if not state.file then return end
    local lines = { "# NPC Kill Log. One \"Name: count\" line per NPC." }
    local byName = {}
    for name, n in pairs(state.kills) do byName[#byName + 1] = { name = name, count = n } end
    table.sort(byName, function(a, b) return a.name:lower() < b.name:lower() end)
    for _, e in ipairs(byName) do lines[#lines + 1] = e.name .. ": " .. e.count end

    local tmp = state.file .. ".tmp"
    local f = io.open(tmp, "w")
    if not f then
        log("cannot write " .. tmp)
        return
    end
    f:write(table.concat(lines, "\n") .. "\n")
    f:close()
    -- Windows rename does not replace an existing file, so remove the old one first
    os.remove(state.file)
    local okRename, err = os.rename(tmp, state.file)
    if not okRename then log("cannot rename " .. tmp .. ": " .. tostring(err)) end
end

local function scheduleSave()
    if state.savePending then return end
    state.savePending = true
    ExecuteWithDelay(2000, function()
        ExecuteInGameThread(saveNow)
    end)
end

-- Works out which character is playing and loads its counts. Kills counted before the character
-- was known are kept and merged in.
local function ensureCharacter()
    local pc = localController()
    if not pc then return state.key ~= nil end
    local okN, name = pcall(function() return pc.PlayerState:GetPlayerName():ToString() end)
    if not okN or not name or name == "" then return state.key ~= nil end

    local folder = savedFolder()
    local guid = folder and characterGuid(folder, name)
    local safe = name:gsub("[^%w%-_]", "_")
    local key = safe .. (guid and ("-" .. guid:sub(1, 8)) or "")
    if key == state.key then return true end

    if state.key and state.savePending then saveNow() end
    local pending = (state.key == nil) and state.kills or {}
    state.key = key
    state.file = (folder or MOD_FOLDER) .. (folder and "\\" or "/") .. "NpcKillLog-" .. key .. ".txt"
    state.kills = loadCounts(state.file)
    local merged = 0
    for n, c in pairs(pending) do
        state.kills[n] = (state.kills[n] or 0) + c
        merged = merged + c
    end
    if merged > 0 then scheduleSave() end
    local types, total = 0, 0
    for _, c in pairs(state.kills) do types = types + 1; total = total + c end
    log("character " .. name .. ": " .. killSummary(total, types) .. " (" .. state.file .. ")")
    return true
end

-- ---------------------------------------------------------------------------
-- Window
-- ---------------------------------------------------------------------------

local ui = { open = false, frame = nil, list = nil, header = nil, search = nil, scroll = nil, lastFilter = nil }
local refreshWindow   -- defined below

local GOLD = { R = 1.0, G = 0.78, B = 0.35, A = 1.0 }
local WHITE = { R = 0.95, G = 0.93, B = 0.88, A = 1.0 }
local GREY = { R = 0.65, G = 0.63, B = 0.6, A = 1.0 }

local classCache = {}
local function findClass(path)
    local c = classCache[path]
    if c and isValid(c) then return c end
    c = nil
    pcall(function() c = StaticFindObject(path) end)
    if not isValid(c) and path:sub(1, 6) == "/Game/" then
        -- Blueprint classes may need loading first: "/Game/X/WBP_Y.WBP_Y_C" -> load "/Game/X/WBP_Y"
        pcall(function() LoadAsset((path:gsub("%.[^%.]*$", ""))) end)
        pcall(function() c = StaticFindObject(path) end)
    end
    if not isValid(c) then return nil end
    classCache[path] = c
    return c
end

local function newWidget(className, tree)
    local c = findClass("/Script/UMG." .. className)
    if not c then return nil end
    local ok, w = pcall(StaticConstructObject, c, tree)
    return ok and w or nil
end

local function newText(tree, textClass, text, size, color)
    local ok, tb = pcall(StaticConstructObject, textClass, tree)
    if not ok or not tb then return nil end
    pcall(function()
        local font = tb.Font
        font.Size = size
        tb:SetFont(font)
    end)
    pcall(function() tb:SetColorAndOpacity({ SpecifiedColor = color, ColorUseRule = 0 }) end)
    pcall(function() tb:SetText(FText(text)) end)
    return tb
end

local function widgetLibrary()
    local lib = nil
    pcall(function() lib = StaticFindObject("/Script/UMG.Default__WidgetBlueprintLibrary") end)
    return isValid(lib) and lib or nil
end

local function setInputForWindow(on)
    if not cfg.CaptureMouse then return end
    local pc = localController()
    local lib = widgetLibrary()
    if not pc or not lib then return end
    pcall(function() pc.bShowMouseCursor = on end)
    if on then
        local focus = ui.search or ui.frame
        if not pcall(function() lib:SetInputMode_UIOnlyEx(pc, focus, 0, false) end) then
            pcall(function() lib:SetInputMode_GameAndUIEx(pc, focus, 0, false, false) end)
        end
    else
        pcall(function() lib:SetInputMode_GameOnly(pc, false) end)
    end
end

-- The pause menu entry, set up further down; the window only needs to know it for the style
local menu = { pm = nil, seen = {}, button = nil, buttonAddr = nil, hooked = false, announced = false, nextSearch = 0 }
local hookButtonClicks   -- defined with the pause menu entry below
local BUTTON_CLASS = "/Game/UI/Common/WBP_DomAllCapsButton.WBP_DomAllCapsButton_C"

-- One of the game's own menu buttons, styled like the pause menu's SETTINGS button when known
local function newGameButton(pc, label)
    local lib = widgetLibrary()
    local cls = findClass(BUTTON_CLASS)
    if not (pc and lib and cls) then return nil end
    local okB, b = pcall(function() return lib:Create(pc, cls, pc) end)
    if not okB or not isValid(b) then return nil end
    local settings = nil
    pcall(function() settings = menu.pm and menu.pm.SettingsButton end)
    if isValid(settings) then pcall(function() b:SetStyle(settings.Style) end) end
    pcall(function() b:SetLabelText(FText(label)) end)
    return b
end

local function toggleLabel(t)
    return t.label .. ": " .. (cfg[t.key] and "ON" or "OFF")
end

local function flipToggle(t)
    cfg[t.key] = not cfg[t.key]
    if isValid(t.button) then pcall(function() t.button:SetLabelText(FText(toggleLabel(t))) end) end
    saveToggles()
    log(toggleLabel(t))
end

local function buildWindow()
    local pc = localController()
    local lib = widgetLibrary()
    if not pc or not lib then
        log("cannot open the window yet: no local player")
        return false
    end
    local panelClass = findClass("/Game/UI/Panels/WBP_Panel.WBP_Panel_C")
    local textClass = findClass("/Game/UI/Common/WBP_DomTextBlock.WBP_DomTextBlock_C") or findClass("/Script/UMG.TextBlock")
    if not panelClass or not textClass then
        log("cannot open the window: the game's panel widget was not found")
        return false
    end

    local okF, frame = pcall(function() return lib:Create(pc, panelClass, pc) end)
    if not okF or not isValid(frame) then
        log("cannot open the window: creating the panel failed")
        return false
    end
    local tree = frame.WidgetTree
    local content = nil
    pcall(function() content = frame.PanelContent end)
    if not isValid(content) then
        log("cannot open the window: the panel has no PanelContent slot (game update?)")
        return false
    end

    local size = newWidget("SizeBox", tree)
    local column = newWidget("VerticalBox", tree)
    local scroll = newWidget("ScrollBox", tree)
    local search = newWidget("EditableTextBox", tree)
    if not (size and column and scroll and search) then
        log("cannot open the window: a UMG widget class was not found")
        return false
    end
    pcall(function() size:SetWidthOverride(cfg.PanelWidth) end)
    pcall(function() size:SetHeightOverride(cfg.PanelHeight) end)
    size:AddChild(column)

    local title = newText(tree, textClass, "NPC KILL LOG", 30, GOLD)
    local header = newText(tree, textClass, "", 16, GREY)
    local list = newText(tree, textClass, "", cfg.FontSize, WHITE)
    local footer = newText(tree, textClass, "Esc to close   |   type to search   |   PageUp/PageDown to scroll", 14, GREY)
    local closeButton = newGameButton(pc, "CLOSE")

    -- The two message switches, each on its own row above CLOSE
    local toggleButtons = {}
    local toggleAddrs = {}
    for _, t in ipairs(TOGGLES) do
        local b = newGameButton(pc, toggleLabel(t))
        if b then
            t.button = b
            toggleButtons[#toggleButtons + 1] = b
            local okA, a = pcall(function() return b:GetAddress() end)
            if okA and a then toggleAddrs[a] = t end
        end
    end

    local function addRow(widget, fill, padBottom)
        if not widget then return end
        local okS, slot = pcall(function() return column:AddChildToVerticalBox(widget) end)
        if okS and slot then
            pcall(function() slot:SetPadding({ Left = 0, Top = 0, Right = 0, Bottom = padBottom or 6 }) end)
            if fill then pcall(function() slot:SetSize({ SizeRule = 1, Value = 1.0 }) end) end
        end
    end
    addRow(title, false, 2)
    addRow(header, false, 10)
    pcall(function() search:SetHintText(FText("Search NPCs")) end)
    addRow(search, false, 10)
    addRow(scroll, true, 8)
    addRow(footer, false, 6)
    for _, b in ipairs(toggleButtons) do addRow(b, false, 6) end
    addRow(closeButton, false, 0)
    if list then scroll:AddChild(list) end

    content:AddChild(size)
    local okV = pcall(function() frame:AddToViewport(9000) end)
    if not okV then
        log("cannot open the window: AddToViewport failed")
        return false
    end
    ui.frame, ui.list, ui.header, ui.search, ui.scroll, ui.lastFilter = frame, list, header, search, scroll, nil
    ui.closeAddr = nil
    if closeButton then pcall(function() ui.closeAddr = closeButton:GetAddress() end) end
    ui.toggleAddrs = toggleAddrs
    -- Opened with OpenKey and no pause menu entry, nothing else has started watching clicks yet
    hookButtonClicks()
    return true
end

refreshWindow = function()
    if not ui.open or not isValid(ui.list) then return end
    local filter = nil
    if isValid(ui.search) then
        local okT, t = pcall(function() return ui.search:GetText():ToString() end)
        if okT and t and trim(t) ~= "" then filter = trim(t):lower() end
    end
    ui.lastFilter = filter or ""

    local entries = sortedEntries(filter and lookupKey(filter))
    local lines = {}
    for i, e in ipairs(entries) do lines[i] = e.name .. ": " .. formatCount(e.count) end
    local text
    if #lines > 0 then
        text = table.concat(lines, "\n")
    elseif filter then
        text = "No NPCs match \"" .. filter .. "\"."
    else
        text = "No kills yet. Go hunting."
    end
    pcall(function() ui.list:SetText(FText(text)) end)

    local types, total = 0, 0
    for _, c in pairs(state.kills) do types = types + 1; total = total + c end
    local head = killSummary(total, types)
    if filter then head = head .. "   |   showing " .. #entries end
    pcall(function() ui.header:SetText(FText(head)) end)
end

local function closeWindow()
    if not ui.open then return end
    ui.open = false
    if isValid(ui.frame) then pcall(function() ui.frame:SetVisibility(1) end) end   -- 1 = Collapsed
    setInputForWindow(false)
end

-- true while the pause menu is showing; nil when that cannot be told
local function pauseMenuShowing()
    local pm = menu.pm
    if not isValid(pm) then return false end
    local okA, active = pcall(function() return pm:IsActivated() end)
    if okA and type(active) == "boolean" then return active end
    local okV, visible = pcall(function() return pm:IsVisible() end)
    if okV and type(visible) == "boolean" then return visible end
    return nil
end

local function openWindow()
    if ui.open then return end
    ensureCharacter()
    if not isValid(ui.frame) or not isValid(ui.list) then
        ui.frame = nil
        if not buildWindow() then return end
    else
        pcall(function() ui.frame:SetVisibility(0) end)   -- 0 = Visible
    end
    ui.open = true
    refreshWindow()
    setInputForWindow(true)
    -- Watch the search box while the window is open; there is no text changed callback from Lua
    LoopAsync(250, function()
        if not ui.open then return true end
        ExecuteInGameThread(function()
            if not ui.open then return end
            if not isValid(ui.search) then return end
            local okT, t = pcall(function() return ui.search:GetText():ToString() end)
            local filter = (okT and t and trim(t):lower()) or ""
            if filter ~= ui.lastFilter then refreshWindow() end
        end)
        return false
    end)
end

-- ---------------------------------------------------------------------------
-- Kill message
-- ---------------------------------------------------------------------------
-- A second WBP_Panel instance whose widget tree root is swapped for a bare canvas before it is
-- shown, so only our line of text is drawn (no frame). It ignores the mouse.

local toast = { frame = nil, text = nil, shownId = 0 }

local function buildToast()
    local pc = localController()
    local lib = widgetLibrary()
    local panelClass = findClass("/Game/UI/Panels/WBP_Panel.WBP_Panel_C")
    local textClass = findClass("/Game/UI/Common/WBP_DomTextBlock.WBP_DomTextBlock_C") or findClass("/Script/UMG.TextBlock")
    if not (pc and lib and panelClass and textClass) then return false end
    local okF, frame = pcall(function() return lib:Create(pc, panelClass, pc) end)
    if not okF or not isValid(frame) then return false end
    local tree = frame.WidgetTree
    local canvas = newWidget("CanvasPanel", tree)
    local text = newText(tree, textClass, "", cfg.MessageFontSize, GOLD)
    if not (canvas and text) then return false end
    if not pcall(function() tree.RootWidget = canvas end) then return false end
    pcall(function() text:SetJustification(1) end)   -- 1 = Center
    local okS, slot = pcall(function() return canvas:AddChildToCanvas(text) end)
    if okS and slot then
        -- Centred, a little below the middle of the screen, above the hotbar
        pcall(function() slot:SetAnchors({ Minimum = { X = 0.5, Y = 0.72 }, Maximum = { X = 0.5, Y = 0.72 } }) end)
        pcall(function() slot:SetAlignment({ X = 0.5, Y = 0.5 }) end)
        pcall(function() slot:SetAutoSize(true) end)
        pcall(function() slot:SetPosition({ X = 0, Y = 0 }) end)
    end
    pcall(function() frame:SetVisibility(3) end)   -- 3 = HitTestInvisible
    if not pcall(function() frame:AddToViewport(850) end) then return false end
    toast.frame, toast.text = frame, text
    return true
end

local function showKillMessage(message)
    if not (isValid(toast.frame) and isValid(toast.text)) then
        toast.frame, toast.text = nil, nil
        if not buildToast() then
            if not toast.warned then
                toast.warned = true
                log("could not show kill messages on screen")
            end
            return
        end
    end
    pcall(function() toast.text:SetText(FText(message)) end)
    pcall(function() toast.frame:SetVisibility(3) end)
    -- Each message hides itself after MessageSeconds unless a newer one replaced it
    toast.shownId = toast.shownId + 1
    local id = toast.shownId
    ExecuteWithDelay(math.max(1, cfg.MessageSeconds) * 1000, function()
        ExecuteInGameThread(function()
            if toast.shownId == id and isValid(toast.frame) then
                pcall(function() toast.frame:SetVisibility(1) end)   -- 1 = Collapsed
            end
        end)
    end)
end

local function scrollBy(pages)
    if not ui.open or not isValid(ui.scroll) then return end
    pcall(function()
        local offset = ui.scroll:GetScrollOffset() + pages * cfg.PanelHeight * 0.8
        local maxOffset = ui.scroll:GetScrollOffsetOfEnd()
        ui.scroll:SetScrollOffset(math.max(0, math.min(maxOffset, offset)))
    end)
end

-- ---------------------------------------------------------------------------
-- Kill counting
-- ---------------------------------------------------------------------------

local recentKills = {}   -- killed actor address -> os.clock(), so one death is never counted twice

-- Boss detection from the game's own setup rather than a hand made list
local BOSS_BAR_CLASS = "/Game/Gameplay/AI/Components/BP_BossAiHealthBarComponent.BP_BossAiHealthBarComponent_C"
local MINIBOSS_BASES = {
    "/Game/Gameplay/AI/BaseAIClasses/Characters/BP_AI_Miniboss_Biped_Base.BP_AI_Miniboss_Biped_Base_C",
    "/Game/Gameplay/AI/BaseAIClasses/Characters/BP_AI_Miniboss_Gigantic_Base.BP_AI_Miniboss_Gigantic_Base_C",
}

local function nameSet(list)
    local set = {}
    for part in list:gmatch("[^,]+") do
        local k = lookupKey(trim(part))
        if k ~= "" then set[k] = true end
    end
    return set
end
local extraBosses = nameSet(cfg.ExtraBosses)
local notBosses = nameSet(cfg.NotBosses)

-- Only classes that are already loaded: if the boss bar or a miniboss base is not loaded, the
-- creature that just died cannot be using it, and loading assets inside the death handler is not safe
local function loadedClass(path)
    local c = nil
    pcall(function() c = StaticFindObject(path) end)
    return isValid(c) and c or nil
end

local bossByClass = {}   -- class name -> true/false

local function isBoss(ai, name)
    local k = lookupKey(name)
    if notBosses[k] then return false end
    if extraBosses[k] then return true end
    local okC, className = pcall(function() return ai:GetClass():GetFName():ToString() end)
    className = okC and className or ""
    local cached = bossByClass[className]
    if cached ~= nil then return cached end

    local boss, why = false, nil
    local bar = loadedClass(BOSS_BAR_CLASS)
    if bar then
        local okB, comp = pcall(function() return ai:GetComponentByClass(bar) end)
        if okB and isValid(comp) then boss, why = true, "boss health bar" end
    end
    if not boss then
        for _, path in ipairs(MINIBOSS_BASES) do
            local base = loadedClass(path)
            local okI, isA = false, false
            if base then okI, isA = pcall(function() return ai:IsA(base) end) end
            if okI and isA then boss, why = true, "miniboss base class"; break end
        end
    end
    -- Class name rules, checked against the wiki's boss list (2026-09-28): the vault Rat King and
    -- Plague King (ColossalRat, ColossalFungalRat) have neither a boss bar nor a miniboss base, and
    -- dragon hatchlings have a boss bar but are not bosses
    local lowerClass = className:lower()
    if lowerClass:find("hatchling", 1, true) then boss, why = false, nil
    elseif not boss and (lowerClass:find("boss", 1, true) or lowerClass:find("colossal", 1, true)) then
        boss, why = true, "class name"
    end

    bossByClass[className] = boss
    if boss then log(name .. " counts as a boss (" .. why .. ")") end
    return boss
end

-- Full names of the local player's pawn, newest first. A pawn that dies and respawns is a new
-- object with a new name, so the last few are kept: a creature hit before the respawn and
-- finished after it still has the old pawn in its damage list
local myPawns = {}

local function rememberMyPawn()
    local pc = localController()
    if not pc then return end
    local okP, pawn = pcall(function() return pc:K2_GetPawn() end)
    if not okP or not isValid(pawn) then return end
    local okN, name = pcall(function() return pawn:GetFullName() end)
    if not okN or type(name) ~= "string" or name == "" or name == myPawns[1] then return end
    table.insert(myPawns, 1, name)
    while #myPawns > 3 do table.remove(myPawns) end
end

-- Who damaged this AI, from its controller's ThreatSystem.DamageInstigators.
-- Returns true when the local player did, false when only others did (or nobody, e.g. a fall),
-- nil when the list could not be read; the second value lists the instigators for the log
local function killedByMe(ai)
    rememberMyPawn()
    local ctrl = nil
    pcall(function() ctrl = ai:GetController() end)
    if not isValid(ctrl) then pcall(function() ctrl = ai.Controller end) end
    if not isValid(ctrl) then return nil, "no controller" end
    local okT, threats = pcall(function() return ctrl.ThreatSystem end)
    if not okT or not isValid(threats) then return nil, "no ThreatSystem" end

    local myController = ""
    pcall(function() myController = localController():GetFullName() end)
    local mine = false
    local seen = {}
    local okE = pcall(function()
        threats.DamageInstigators:ForEach(function(_, element)
            local who = element:get()
            if not isValid(who) then return end
            local okN, name = pcall(function() return who:GetFullName() end)
            if not okN or type(name) ~= "string" then return end
            seen[#seen + 1] = name
            if name == myController then mine = true end
            for _, pawnName in ipairs(myPawns) do
                if name == pawnName then mine = true end
            end
        end)
    end)
    if not okE then return nil, "DamageInstigators unreadable" end
    return mine, (#seen > 0 and table.concat(seen, ", ") or "nobody")
end

local warnedUnreadable = false

local function onKill(ai)
    if not isValid(ai) then return end

    local okA, addr = pcall(function() return ai:GetAddress() end)
    local now = os.clock()
    if okA and addr then
        local last = recentKills[addr]
        if last and now - last < 2 then return end
        recentKills[addr] = now
    end

    if cfg.OnlyMyKills then
        local mine, who = killedByMe(ai)
        if mine == false then
            if cfg.LogKills then log("not counted, not your kill: " .. resolveName(ai) .. " (damage by " .. who .. ")") end
            return
        elseif mine == nil and not warnedUnreadable then
            -- Counting it is the safer mistake in single player; say so once
            warnedUnreadable = true
            log("could not tell who killed " .. resolveName(ai) .. " (" .. who .. "), counted anyway; later ones are not logged")
        end
    end

    local name = resolveName(ai)
    ensureCharacter()
    state.kills[name] = (state.kills[name] or 0) + 1
    local message = "Your " .. name .. " kill count is now: " .. formatCount(state.kills[name]) .. "."
    if cfg.LogKills then log(message) end
    local show = cfg.ShowKillMessages
    if isBoss(ai, name) then show = cfg.ShowBossKillMessages end
    -- Shown on a later tick, outside the game's kill handler
    if show then
        ExecuteWithDelay(1, function() ExecuteInGameThread(function() showKillMessage(message) end) end)
    end
    scheduleSave()
    if ui.open then refreshWindow() end

    -- Forget old entries now and then so the table does not grow forever
    for a, t in pairs(recentKills) do
        if now - t > 10 then recentKills[a] = nil end
    end
end

-- The dying creature is the hook's self. The Blueprint class is not loaded until a world is, so
-- registering fails until then; it is retried every 5 s once the player has a pawn, and never
-- registered twice (a hook on a Blueprint function survives a return to the main menu)
local DEATH_HOOK = "/Game/Gameplay/AI/BP_DominionAICharacter.BP_DominionAICharacter_C:BP_OnDeath"
local deathHook = { armed = false, tries = 0 }

local function armDeathHook()
    if deathHook.armed then return end
    local pc = localController()
    local okP, pawn = false, nil
    if pc then okP, pawn = pcall(function() return pc:K2_GetPawn() end) end
    if not okP or not isValid(pawn) then return end
    deathHook.tries = deathHook.tries + 1
    local okHook, hookErr = pcall(RegisterHook, DEATH_HOOK, function(self)
        local okCall, err = pcall(function() onKill(self:get()) end)
        if not okCall then log("error counting a kill: " .. tostring(err)) end
    end)
    if okHook then
        deathHook.armed = true
        log("kill counting armed (try " .. deathHook.tries .. ")")
    elseif deathHook.tries == 1 or deathHook.tries % 12 == 0 then
        log("death hook not ready yet, will retry: " .. tostring(hookErr))
    end
end

-- Runs off the game thread; the work is queued onto it. Also keeps the pawn list fresh so a
-- respawned player still gets credit for creatures hit before dying
LoopAsync(5000, function()
    ExecuteInGameThread(function()
        armDeathHook()
        rememberMyPawn()
    end)
    return false
end)

-- The original native hooks, from before BP_OnDeath. Both run for the same death (the dying AI is
-- their only argument; recentKills keeps it to one count) but give no way to tell who made the
-- kill. To switch back, uncomment this block and remove the LoopAsync above; OnlyMyKills still
-- should still work with them, since onKill reads the damage list itself (untested that way).
-- local KILL_HOOKS = {
--     "/Script/Dominion.AiAttackTicketsManager:OnAiDeath",
--     "/Script/Dominion.AIAudioManagerComponent:HandleDeath",
-- }
-- local killHooks = 0
-- for _, path in ipairs(KILL_HOOKS) do
--     local okHook, hookErr = pcall(RegisterHook, path, function(self, dead)
--         local okCall, err = pcall(function() onKill(dead:get()) end)
--         if not okCall then log("error counting a kill: " .. tostring(err)) end
--     end)
--     if okHook then killHooks = killHooks + 1 else log("could not hook " .. path .. ": " .. tostring(hookErr)) end
-- end
-- if killHooks == 0 then log("no death hook could be registered, kills will not be counted") end

-- ---------------------------------------------------------------------------
-- Keys
-- ---------------------------------------------------------------------------

-- "F4", "K" or "CTRL+SHIFT+K" -> key, { modifiers }
local function parseKey(spec)
    local mods = {}
    local keyName = nil
    for part in spec:upper():gmatch("[^+%s]+") do
        if part == "CTRL" or part == "CONTROL" then mods[#mods + 1] = ModifierKey.CONTROL
        elseif part == "SHIFT" then mods[#mods + 1] = ModifierKey.SHIFT
        elseif part == "ALT" then mods[#mods + 1] = ModifierKey.ALT
        else keyName = part end
    end
    local key = keyName and Key[keyName]
    return key, mods
end

-- Closes the pause menu when it is up, then opens the window a moment later, once the menu and
-- its backdrop are gone and the game has handed back input. Opening on top of the pause menu leaves
-- the window behind the menu's backdrop and the game paused. fromMenu: the pause menu entry was
-- clicked, so the menu is up even when pauseMenuShowing cannot tell.
local function openAfterPauseMenu(fromMenu)
    local pm = menu.pm
    if isValid(pm) and (fromMenu or pauseMenuShowing()) then
        pcall(function() pm:Resume() end)
        ExecuteWithDelay(250, function() ExecuteInGameThread(openWindow) end)
    else
        openWindow()
    end
end

local function toggleWindow()
    ExecuteInGameThread(function()
        if ui.open then closeWindow() else openAfterPauseMenu() end
    end)
end

if cfg.OpenKey ~= "" then
    local openKey, openMods = parseKey(cfg.OpenKey)
    if not openKey then
        log("unknown OpenKey " .. cfg.OpenKey .. ", no key bound")
    elseif #openMods > 0 then
        RegisterKeyBind(openKey, openMods, toggleWindow)
    else
        RegisterKeyBind(openKey, toggleWindow)
    end
end

-- ---------------------------------------------------------------------------
-- Pause menu entry
-- ---------------------------------------------------------------------------
-- The pause menu (WBP_PauseMenuScreen_C) lists its entries as WBP_DomAllCapsButton_C buttons in
-- VerticalBox_PauseMenu. Our entry is one more button in that list, just above the two exits.

local EXIT_BUTTONS = { "ExitToMainMenuButton", "ExitToDesktopMenu" }

local function isRealPauseMenu(pm)
    if not isValid(pm) then return false end
    local okN, n = pcall(function() return pm:GetFName():ToString() end)
    return okN and type(n) == "string" and n:sub(1, 9) ~= "Default__"
end

local function findPauseMenu(allowSearch)
    if isRealPauseMenu(menu.pm) then return menu.pm end
    for i = #menu.seen, 1, -1 do
        if isRealPauseMenu(menu.seen[i]) then
            menu.pm = menu.seen[i]
            menu.seen = {}
            return menu.pm
        end
    end
    menu.seen = {}
    -- Last resort: a search of every object, slow (tens of ms), so at most every 10 seconds
    if allowSearch and os.clock() >= menu.nextSearch then
        menu.nextSearch = os.clock() + 10
        local ok, pm = pcall(FindFirstOf, "WBP_PauseMenuScreen_C")
        if ok and isRealPauseMenu(pm) then menu.pm = pm; return pm end
    end
    return nil
end

local function inBox(box, w)
    local ok, idx = pcall(function() return box:GetChildIndex(w) end)
    return ok and type(idx) == "number" and idx >= 0
end

-- A widget's vertical box slot settings as plain values, so they survive the widget leaving the box
local function slotLayout(w)
    local layout = nil
    pcall(function()
        local s = w.Slot
        local pad, size = s.Padding, s.Size
        layout = {
            padding = { Left = pad.Left, Top = pad.Top, Right = pad.Right, Bottom = pad.Bottom },
            size = { SizeRule = size.SizeRule, Value = size.Value },
            h = s.HorizontalAlignment,
            v = s.VerticalAlignment,
        }
    end)
    return layout
end

local function addToBox(box, w, layout)
    local okS, slot = pcall(function() return box:AddChildToVerticalBox(w) end)
    if not (okS and slot and layout) then return end
    pcall(function() slot:SetPadding(layout.padding) end)
    pcall(function() slot:SetSize(layout.size) end)
    pcall(function() slot:SetHorizontalAlignment(layout.h) end)
    pcall(function() slot:SetVerticalAlignment(layout.v) end)
end

hookButtonClicks = function()
    if menu.hooked then return end
    menu.hooked = true
    local ok, err = pcall(RegisterHook, "/Script/CommonUI.CommonButtonBase:HandleButtonClicked", function(self)
        local okA, addr = pcall(function() return self:get():GetAddress() end)
        if not okA or not addr then return end
        -- Only note the click here; the window is built on a later tick, outside the click handler
        if addr == menu.buttonAddr then
            ExecuteWithDelay(1, function() ExecuteInGameThread(function() openAfterPauseMenu(true) end) end)
        elseif ui.closeAddr and addr == ui.closeAddr then
            ExecuteWithDelay(1, function() ExecuteInGameThread(closeWindow) end)
        elseif ui.toggleAddrs and ui.toggleAddrs[addr] then
            local t = ui.toggleAddrs[addr]
            ExecuteWithDelay(1, function() ExecuteInGameThread(function() flipToggle(t) end) end)
        end
    end)
    if not ok then log("could not watch button clicks, the pause menu entry will not work: " .. tostring(err)) end
end

-- Makes sure our entry is in the pause menu. Cheap when it already is.
local function ensureMenuButton(allowSearch)
    if not cfg.ShowInPauseMenu then return end
    local pm = findPauseMenu(allowSearch)
    if not pm then return end
    local box = nil
    pcall(function() box = pm.VerticalBox_PauseMenu end)
    if not isValid(box) then return end
    if isValid(menu.button) and inBox(box, menu.button) then return end

    local b = newGameButton(localController(), cfg.MenuLabel)
    if not b then return end
    local settings = nil
    pcall(function() settings = pm.SettingsButton end)
    local ourLayout = isValid(settings) and slotLayout(settings) or nil

    -- Take the exits out, add our entry, put the exits back with their own spacing
    local exits = {}
    for _, name in ipairs(EXIT_BUTTONS) do
        local e = nil
        pcall(function() e = pm[name] end)
        if isValid(e) and inBox(box, e) then exits[#exits + 1] = { widget = e, layout = slotLayout(e) } end
    end
    for _, e in ipairs(exits) do pcall(function() box:RemoveChild(e.widget) end) end
    addToBox(box, b, ourLayout)
    for _, e in ipairs(exits) do addToBox(box, e.widget, e.layout) end

    menu.button = b
    pcall(function() menu.buttonAddr = b:GetAddress() end)
    hookButtonClicks()
    if not menu.announced then
        menu.announced = true
        log("added " .. cfg.MenuLabel .. " to the pause menu")
    end
end

-- The pause menu is created the first time Esc is pressed and its widgets a moment later, so
-- check a few times after it appears or Esc is pressed
local function scheduleMenuChecks()
    for i, delay in ipairs({ 100, 400, 1000, 2500 }) do
        ExecuteWithDelay(delay, function()
            ExecuteInGameThread(function() ensureMenuButton(i >= 3) end)
        end)
    end
end

if cfg.ShowInPauseMenu then
    pcall(NotifyOnNewObject, "/Script/Dominion.PauseMenuScreen", function(obj)
        menu.seen[#menu.seen + 1] = obj
        scheduleMenuChecks()
    end)
end

pcall(RegisterKeyBind, Key.ESCAPE, function()
    if ui.open then ExecuteInGameThread(closeWindow) end
    if cfg.ShowInPauseMenu then scheduleMenuChecks() end
end)
pcall(RegisterKeyBind, Key.PAGE_UP, function() ExecuteInGameThread(function() scrollBy(-1) end) end)
pcall(RegisterKeyBind, Key.PAGE_DOWN, function() ExecuteInGameThread(function() scrollBy(1) end) end)

-- A new world or the main menu replaces the viewport and the player controller
pcall(RegisterLoadMapPostHook, function()
    ExecuteInGameThread(function()
        if state.savePending then saveNow() end
        ui.open, ui.frame = false, nil
        toast.frame, toast.text = nil, nil
        state.pc = nil
        menu.pm, menu.button, menu.buttonAddr, menu.seen = nil, nil, nil, {}
    end)
    ExecuteWithDelay(5000, function() ExecuteInGameThread(function() ensureCharacter() end) end)
end)

if cfg.ShowInPauseMenu and cfg.OpenKey ~= "" then
    log("ready. Open the kill log from the pause menu (Esc > " .. cfg.MenuLabel .. ") or with " .. cfg.OpenKey)
elseif cfg.ShowInPauseMenu then
    log("ready. Open the kill log from the pause menu (Esc > " .. cfg.MenuLabel .. ")")
elseif cfg.OpenKey ~= "" then
    log("ready. Open the kill log with " .. cfg.OpenKey)
else
    log("ShowInPauseMenu is false and no OpenKey is set, so the kill log cannot be opened")
end
